config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, 
             :controllers => { :registrations => "user_registrations" }
  
  resources :users

  resources :products do
    resources :comments
  end
  
  get 'static_pages/products'
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  get 'static_pages/faq'

  post 'static_pages/thank_you'

  post 'payments/create'

  resources :orders, only: [:index, :show, :create, :destroy]

  root 'static_pages#landing_page'

   end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :comments
  belongs_to :users


  validates :name, presence: true
  validates :description, presence: true
  

  def average_rating
    comments.average(:rating).to_f
  end

  def price_in_cents
    (price * 100).to_i
  end


end
 
 

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      if Rails.env.development? #checks to see if in dev mode
        @products = Product.where("name LIKE ?", "%#{search_term}%").paginate(:page => params[:page], :per_page => 3)
      else
        @products = Product.where("name ilike ?", "%#{search_term}%").paginate(:page => params[:page], :per_page => 3)
      end
    else
      @products = Product.all.paginate(:page => params[:page], :per_page => 3)
    end
  end
  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
  end
  

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
	<% @comments.each do |comment| %>
		<div class="row">
			<hr>
			<p>By: <%= comment.user.first_name %><br><small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em>
			<% if signed_in? && current_user.admin? %>
			  <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %><% end %></small></p>
			<div class="rated" data-score="<%= comment.rating %>"></div>
			<p><%= comment.body %></p>
		</div>
	<% end %>
	<%= will_paginate @comments %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%=f.label :price %><br>
    <%=f.text_field :price %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
<div id="rate">
	<h4>Add a review</h4>
	<%= form_for([@product, @product.comments.build], remote: true) do |f| %>
		<p>
			<div class="rating"></div>
		</p>
		<div class="form-group" id="new-comment">
			<%= f.label :body, "Comments" %><br>
			<%= f.text_area :body, class: 'form-control', placeholder: 'Your review here', rows: '5' %>
		</div>
		
		<p id="new-comment">
			<%= f.submit "Submit", class: 'btn btn-primary' %>
		</p>

	<% end %>
</div>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
<div class="col-lg-4 col-md-4 col-sm-6">
	<div class="product"><%= link_to(image_tag(product.image_url), product, :class=>"img-thumbnail") %>
    <h4 id="productname"><%= link_to product.name, product %></h4>
    <p id="product-index">
        $<%= product.price %></p>
    </div>
  <div class="show-index-links">
    <% if user_signed_in? && current_user.admin? %>
      <%= link_to 'Detailed View' .html_safe, product %>
      <%= link_to 'Edit' .html_safe, edit_product_path(product) %>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %> |

    <% else %>
      <%= link_to 'Detailed view' .html_safe, product %>
    <% end %>
  </div>
 </div>
 <% end %>

app/views/products/edit.html.erb
<h2>Edit Product</h2>

<%= render 'form' %>

<div class="edit-links">
<%= link_to 'Show', @product %> |
<%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
 <div class="row" id="index">
    <h1>Products</h1>
    <% cache (cache_key_for_products) do %>
       <%= render @products %>
    <% end %>
  </div>


<div class="container" id="new-product">
   <% if user_signed_in? && current_user.admin? %>
      <%= link_to 'New Product', new_product_path, class: "btn btn-primary" %>
   <% end %>
 </div>
  

app/views/products/new.html.erb
<h1>New Product</h1>
<div class="container">
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
      <%= render 'form' %>
    </div>
    <div class="col-md-4">
    </div>
  </div>
</div>
<hr>
<div class="container" id="new-page">
  <%= link_to 'Back', products_path, class: "btn btn-primary" %>
</div>

app/views/products/show.html.erb
<div class="container" id="imageshow">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">  
     <div class ="img-thumbnail">
        <%= image_tag(@product.image_url, width: "300px", class: "img-zoom", data_zoom_image: @product.image_url) %>
     </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12" id="about">
       <h3>
          <%= @product.name %>
       </h3>
       <p>
        <strong>Price:</strong>
          <%= number_to_currency(@product.price) %>
       </p>
    
       <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div> </p>
       <p>
          <strong>Description:</strong><br><%= @product.description %>
       </p>
       <p>
         <%= form_tag "/payments/create" do %>
         <%= hidden_field_tag(:product_id, @product.id) %>
         <%= render partial: "shared/stripe_checkout_button" %>
         <% end %>
       </p>
    </div>
  </div>

 <div id="comments">
 <% if current_user && current_user.admin? %>
 <%= link_to 'Edit', edit_product_path(@product) %> |
 <%= link_to 'Back', products_path %>
 <% end %>

 <%= render 'new_comment' %>
 <%= render 'comments' %>

 </div>
</div>